name: Deploy To VM

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Run Tests
      run: go test -v ./...

  update_dev_server:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Update Dev Server
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd apps/lema-be
          git pull origin development
          go build src/main.go
          sudo systemctl restart lema.service